// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wiphone.proto

package protomodel

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Credentials struct {
	Operator string `protobuf:"bytes,1,opt,name=Operator" json:"Operator,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=Username" json:"Username,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=Password" json:"Password,omitempty"`
}

func (m *Credentials) Reset()                    { *m = Credentials{} }
func (m *Credentials) String() string            { return proto1.CompactTextString(m) }
func (*Credentials) ProtoMessage()               {}
func (*Credentials) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Credentials) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *Credentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ConsumptionResponse struct {
	InternetTotal    int64 `protobuf:"varint,1,opt,name=InternetTotal" json:"InternetTotal,omitempty"`
	InternetConsumed int64 `protobuf:"varint,2,opt,name=InternetConsumed" json:"InternetConsumed,omitempty"`
	CallTotal        int32 `protobuf:"varint,3,opt,name=CallTotal" json:"CallTotal,omitempty"`
	CallConsumed     int32 `protobuf:"varint,4,opt,name=CallConsumed" json:"CallConsumed,omitempty"`
	RenewTime        int32 `protobuf:"varint,5,opt,name=RenewTime" json:"RenewTime,omitempty"`
}

func (m *ConsumptionResponse) Reset()                    { *m = ConsumptionResponse{} }
func (m *ConsumptionResponse) String() string            { return proto1.CompactTextString(m) }
func (*ConsumptionResponse) ProtoMessage()               {}
func (*ConsumptionResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *ConsumptionResponse) GetInternetTotal() int64 {
	if m != nil {
		return m.InternetTotal
	}
	return 0
}

func (m *ConsumptionResponse) GetInternetConsumed() int64 {
	if m != nil {
		return m.InternetConsumed
	}
	return 0
}

func (m *ConsumptionResponse) GetCallTotal() int32 {
	if m != nil {
		return m.CallTotal
	}
	return 0
}

func (m *ConsumptionResponse) GetCallConsumed() int32 {
	if m != nil {
		return m.CallConsumed
	}
	return 0
}

func (m *ConsumptionResponse) GetRenewTime() int32 {
	if m != nil {
		return m.RenewTime
	}
	return 0
}

type AnonymousConsumptionRequest struct {
	DeviceId    string       `protobuf:"bytes,1,opt,name=DeviceId" json:"DeviceId,omitempty"`
	Credentials *Credentials `protobuf:"bytes,2,opt,name=Credentials" json:"Credentials,omitempty"`
}

func (m *AnonymousConsumptionRequest) Reset()                    { *m = AnonymousConsumptionRequest{} }
func (m *AnonymousConsumptionRequest) String() string            { return proto1.CompactTextString(m) }
func (*AnonymousConsumptionRequest) ProtoMessage()               {}
func (*AnonymousConsumptionRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *AnonymousConsumptionRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *AnonymousConsumptionRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func init() {
	proto1.RegisterType((*Credentials)(nil), "proto.Credentials")
	proto1.RegisterType((*ConsumptionResponse)(nil), "proto.ConsumptionResponse")
	proto1.RegisterType((*AnonymousConsumptionRequest)(nil), "proto.AnonymousConsumptionRequest")
}

func init() { proto1.RegisterFile("wiphone.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x59, 0x6b, 0xc5, 0xcd, 0xba, 0x20, 0xf1, 0x52, 0xd4, 0x83, 0x14, 0x0f, 0xe2, 0x61,
	0x0f, 0xea, 0x0b, 0x48, 0xbd, 0xec, 0x49, 0x09, 0xeb, 0x03, 0x44, 0x3b, 0x60, 0xa0, 0x9d, 0x89,
	0x99, 0xd4, 0xe2, 0x13, 0xfa, 0x5a, 0x92, 0x84, 0xd4, 0x2d, 0x9e, 0xca, 0xff, 0x7f, 0xc3, 0x3f,
	0x9d, 0x3f, 0x62, 0x3d, 0x1a, 0xfb, 0x41, 0x08, 0x1b, 0xeb, 0xc8, 0x93, 0x2c, 0xe3, 0xa7, 0xd6,
	0x62, 0xd5, 0x38, 0x68, 0x01, 0xbd, 0xd1, 0x1d, 0xcb, 0x73, 0x71, 0xfc, 0x6c, 0xc1, 0x69, 0x4f,
	0xae, 0x5a, 0x5c, 0x2d, 0x6e, 0x96, 0x6a, 0xd2, 0x81, 0xbd, 0x32, 0x38, 0xd4, 0x3d, 0x54, 0x07,
	0x89, 0x65, 0x1d, 0xd8, 0x8b, 0x66, 0x1e, 0xc9, 0xb5, 0x55, 0x91, 0x58, 0xd6, 0xf5, 0xcf, 0x42,
	0x9c, 0x35, 0x84, 0x3c, 0xf4, 0xd6, 0x1b, 0x42, 0x05, 0x6c, 0x09, 0x19, 0xe4, 0xb5, 0x58, 0x6f,
	0xd1, 0x83, 0x43, 0xf0, 0x3b, 0xf2, 0xba, 0x8b, 0x0b, 0x0b, 0x35, 0x37, 0xe5, 0xad, 0x38, 0xcd,
	0x46, 0x0a, 0x81, 0x36, 0x6e, 0x2f, 0xd4, 0x3f, 0x5f, 0x5e, 0x8a, 0x65, 0xa3, 0xbb, 0x2e, 0xa5,
	0x85, 0xdf, 0x28, 0xd5, 0x9f, 0x21, 0x6b, 0x71, 0x12, 0xc4, 0x94, 0x72, 0x18, 0x07, 0x66, 0x5e,
	0x48, 0x50, 0x80, 0x30, 0xee, 0x4c, 0x0f, 0x55, 0x99, 0x12, 0x26, 0xa3, 0x26, 0x71, 0xf1, 0x88,
	0x84, 0xdf, 0x3d, 0x0d, 0x3c, 0xbb, 0xe8, 0x73, 0x00, 0xf6, 0xa1, 0x84, 0x27, 0xf8, 0x32, 0xef,
	0xb0, 0x6d, 0x73, 0x79, 0x59, 0xcb, 0x87, 0x59, 0xcf, 0xf1, 0x82, 0xd5, 0x9d, 0x4c, 0x6f, 0xb1,
	0xd9, 0x23, 0x6a, 0x7f, 0xec, 0xed, 0x28, 0xf2, 0xfb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xde,
	0x35, 0xe4, 0xbb, 0xbc, 0x01, 0x00, 0x00,
}
