mqtt:
   hostname: {{mqtt_hostname}}
   port: {{mqtt_port}}
   topic: {{mqtt_topic}}

database:
   dialect: "mysql"
   uri: "mqtt:123456@tcp(localhost:3306)/mqtt?charset=utf8&parseTime=true"

machinery:
   broker: "redis://localhost:6379/0"
   resultBackend: "redis://localhost:6379/0"
   defaultQueue: "machinery_tasks"

api:
   port: 8080