mqtt:
   hostname: {{mqtt_hostname}}
   port: {{mqtt_port}}
   topic: {{mqtt_topic}}

database:
   dialect: "mysql"
   uri: "root:123456@tcp(localhost:3306)/mqtt?charset=utf8&parseTime=true"

machinery:
   broker: "redis://localhost:6379/0"
   resultBackend: "redis://localhost:6379/0"
   defaultQueue: "machinery_tasks"

api:
   port: 5000

crypto:
   key: 4faf5ac99a48453f85a887634a6e86b8