// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/mensaje.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	proto/mensaje.proto

It has these top-level messages:
	Respuesta
	CredentialsProto
	ErrorProto
	TaskStateResponse
	ConsumptionResponseProto
	AnonymousConsumptionRequest
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TaskState int32

const (
	TaskState_UNKWNOWN TaskState = 0
	TaskState_PENDING  TaskState = 1
	TaskState_RECEIVED TaskState = 2
	TaskState_STARTED  TaskState = 3
	TaskState_RETRY    TaskState = 4
	TaskState_SUCCESS  TaskState = 5
	TaskState_FAILURE  TaskState = 6
)

var TaskState_name = map[int32]string{
	0: "UNKWNOWN",
	1: "PENDING",
	2: "RECEIVED",
	3: "STARTED",
	4: "RETRY",
	5: "SUCCESS",
	6: "FAILURE",
}
var TaskState_value = map[string]int32{
	"UNKWNOWN": 0,
	"PENDING":  1,
	"RECEIVED": 2,
	"STARTED":  3,
	"RETRY":    4,
	"SUCCESS":  5,
	"FAILURE":  6,
}

func (x TaskState) String() string {
	return proto.EnumName(TaskState_name, int32(x))
}
func (TaskState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Respuesta struct {
	Message    string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	StatusCode int32  `protobuf:"varint,2,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
}

func (m *Respuesta) Reset()                    { *m = Respuesta{} }
func (m *Respuesta) String() string            { return proto.CompactTextString(m) }
func (*Respuesta) ProtoMessage()               {}
func (*Respuesta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Respuesta) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Respuesta) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

type CredentialsProto struct {
	Operator string `protobuf:"bytes,1,opt,name=operator" json:"operator,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *CredentialsProto) Reset()                    { *m = CredentialsProto{} }
func (m *CredentialsProto) String() string            { return proto.CompactTextString(m) }
func (*CredentialsProto) ProtoMessage()               {}
func (*CredentialsProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CredentialsProto) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *CredentialsProto) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CredentialsProto) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ErrorProto struct {
	Code        int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *ErrorProto) Reset()                    { *m = ErrorProto{} }
func (m *ErrorProto) String() string            { return proto.CompactTextString(m) }
func (*ErrorProto) ProtoMessage()               {}
func (*ErrorProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ErrorProto) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ErrorProto) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type TaskStateResponse struct {
	State TaskState `protobuf:"varint,1,opt,name=state,enum=main.TaskState" json:"state,omitempty"`
	ETA   int32     `protobuf:"varint,2,opt,name=ETA" json:"ETA,omitempty"`
	Uid   string    `protobuf:"bytes,3,opt,name=uid" json:"uid,omitempty"`
}

func (m *TaskStateResponse) Reset()                    { *m = TaskStateResponse{} }
func (m *TaskStateResponse) String() string            { return proto.CompactTextString(m) }
func (*TaskStateResponse) ProtoMessage()               {}
func (*TaskStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TaskStateResponse) GetState() TaskState {
	if m != nil {
		return m.State
	}
	return TaskState_UNKWNOWN
}

func (m *TaskStateResponse) GetETA() int32 {
	if m != nil {
		return m.ETA
	}
	return 0
}

func (m *TaskStateResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type ConsumptionResponseProto struct {
	InternetTotal    int64 `protobuf:"varint,1,opt,name=internetTotal" json:"internetTotal,omitempty"`
	InternetConsumed int64 `protobuf:"varint,2,opt,name=internetConsumed" json:"internetConsumed,omitempty"`
	CallTotal        int32 `protobuf:"varint,3,opt,name=callTotal" json:"callTotal,omitempty"`
	CallConsumed     int32 `protobuf:"varint,4,opt,name=callConsumed" json:"callConsumed,omitempty"`
	RenewTime        int32 `protobuf:"varint,5,opt,name=renewTime" json:"renewTime,omitempty"`
}

func (m *ConsumptionResponseProto) Reset()                    { *m = ConsumptionResponseProto{} }
func (m *ConsumptionResponseProto) String() string            { return proto.CompactTextString(m) }
func (*ConsumptionResponseProto) ProtoMessage()               {}
func (*ConsumptionResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ConsumptionResponseProto) GetInternetTotal() int64 {
	if m != nil {
		return m.InternetTotal
	}
	return 0
}

func (m *ConsumptionResponseProto) GetInternetConsumed() int64 {
	if m != nil {
		return m.InternetConsumed
	}
	return 0
}

func (m *ConsumptionResponseProto) GetCallTotal() int32 {
	if m != nil {
		return m.CallTotal
	}
	return 0
}

func (m *ConsumptionResponseProto) GetCallConsumed() int32 {
	if m != nil {
		return m.CallConsumed
	}
	return 0
}

func (m *ConsumptionResponseProto) GetRenewTime() int32 {
	if m != nil {
		return m.RenewTime
	}
	return 0
}

type AnonymousConsumptionRequest struct {
	DeviceId    string            `protobuf:"bytes,1,opt,name=deviceId" json:"deviceId,omitempty"`
	Credentials *CredentialsProto `protobuf:"bytes,2,opt,name=credentials" json:"credentials,omitempty"`
}

func (m *AnonymousConsumptionRequest) Reset()                    { *m = AnonymousConsumptionRequest{} }
func (m *AnonymousConsumptionRequest) String() string            { return proto.CompactTextString(m) }
func (*AnonymousConsumptionRequest) ProtoMessage()               {}
func (*AnonymousConsumptionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AnonymousConsumptionRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *AnonymousConsumptionRequest) GetCredentials() *CredentialsProto {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func init() {
	proto.RegisterType((*Respuesta)(nil), "main.Respuesta")
	proto.RegisterType((*CredentialsProto)(nil), "main.CredentialsProto")
	proto.RegisterType((*ErrorProto)(nil), "main.ErrorProto")
	proto.RegisterType((*TaskStateResponse)(nil), "main.TaskStateResponse")
	proto.RegisterType((*ConsumptionResponseProto)(nil), "main.ConsumptionResponseProto")
	proto.RegisterType((*AnonymousConsumptionRequest)(nil), "main.AnonymousConsumptionRequest")
	proto.RegisterEnum("main.TaskState", TaskState_name, TaskState_value)
}

func init() { proto.RegisterFile("proto/mensaje.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x25, 0x4b, 0xbb, 0x2d, 0xb7, 0x03, 0x8c, 0x91, 0x50, 0x04, 0x48, 0x54, 0x11, 0x48, 0xd3,
	0x1e, 0x8a, 0x34, 0x5e, 0x78, 0x2d, 0xa9, 0x87, 0x2a, 0x50, 0x99, 0xdc, 0x94, 0x89, 0x17, 0x90,
	0x69, 0xee, 0x50, 0xa0, 0xb1, 0x83, 0xed, 0x30, 0xf1, 0x8f, 0x7c, 0x14, 0xb2, 0xdd, 0xa4, 0x1d,
	0xbc, 0xf9, 0x9c, 0x63, 0x9d, 0x73, 0xef, 0xf5, 0x35, 0x3c, 0x6c, 0xb4, 0xb2, 0xea, 0x65, 0x8d,
	0xd2, 0x88, 0xef, 0x38, 0xf1, 0x88, 0x0e, 0x6a, 0x51, 0xc9, 0xec, 0x02, 0x12, 0x8e, 0xa6, 0x69,
	0xd1, 0x58, 0x41, 0x53, 0x38, 0xaa, 0xd1, 0x18, 0xf1, 0x0d, 0xd3, 0x68, 0x1c, 0x9d, 0x26, 0xbc,
	0x83, 0xf4, 0x19, 0x8c, 0x8c, 0x15, 0xb6, 0x35, 0x5f, 0xd6, 0xaa, 0xc4, 0xf4, 0x60, 0x1c, 0x9d,
	0x0e, 0x39, 0x04, 0x2a, 0x57, 0x25, 0x66, 0xd7, 0x40, 0x72, 0x8d, 0x25, 0x4a, 0x5b, 0x89, 0x8d,
	0xb9, 0xf4, 0x09, 0x8f, 0xe1, 0x58, 0x35, 0xa8, 0x85, 0x55, 0x7a, 0xeb, 0xd7, 0x63, 0xa7, 0xb5,
	0x06, 0xb5, 0x14, 0x75, 0x70, 0x4b, 0x78, 0x8f, 0x9d, 0xd6, 0x08, 0x63, 0x6e, 0x94, 0x2e, 0xd3,
	0x38, 0x68, 0x1d, 0xce, 0xde, 0x00, 0x30, 0xad, 0x95, 0x0e, 0x09, 0x14, 0x06, 0xbe, 0x9e, 0xc8,
	0xd7, 0xe3, 0xcf, 0x74, 0x0c, 0xa3, 0x12, 0xcd, 0x5a, 0x57, 0x8d, 0xad, 0x94, 0xdc, 0x9a, 0xef,
	0x53, 0xd9, 0x67, 0x78, 0x50, 0x08, 0xf3, 0x63, 0x69, 0x85, 0x45, 0xd7, 0xbc, 0x92, 0x06, 0xe9,
	0x0b, 0x18, 0xba, 0x76, 0x82, 0xd7, 0xbd, 0xf3, 0xfb, 0x13, 0x37, 0x9e, 0xc9, 0xee, 0x5e, 0x50,
	0x29, 0x81, 0x98, 0x15, 0xd3, 0xed, 0x00, 0xdc, 0xd1, 0x31, 0x6d, 0xd5, 0x15, 0xea, 0x8e, 0xd9,
	0x9f, 0x08, 0xd2, 0x5c, 0x49, 0xd3, 0xd6, 0x3e, 0xaf, 0x8b, 0x08, 0x25, 0x3f, 0x87, 0xbb, 0x95,
	0xb4, 0xa8, 0x25, 0xda, 0x42, 0x59, 0xb1, 0xf1, 0x79, 0x31, 0xbf, 0x4d, 0xd2, 0x33, 0x20, 0x1d,
	0x11, 0x9c, 0xb0, 0xf4, 0x99, 0x31, 0xff, 0x8f, 0xa7, 0x4f, 0x21, 0x59, 0x8b, 0xcd, 0x26, 0xb8,
	0xc5, 0xbe, 0xb0, 0x1d, 0x41, 0x33, 0x38, 0x71, 0xa0, 0x77, 0x19, 0xf8, 0x0b, 0xb7, 0x38, 0xe7,
	0xa0, 0x51, 0xe2, 0x4d, 0x51, 0xd5, 0x98, 0x0e, 0x83, 0x43, 0x4f, 0x64, 0x06, 0x9e, 0x4c, 0xa5,
	0x92, 0xbf, 0x6b, 0xe5, 0xde, 0x7a, 0xaf, 0xad, 0x9f, 0x6e, 0x6b, 0xdc, 0x6b, 0x95, 0xf8, 0xab,
	0x5a, 0xe3, 0xbc, 0xec, 0x5e, 0xb9, 0xc3, 0xf4, 0x35, 0x8c, 0xd6, 0xbb, 0xad, 0xf0, 0x1d, 0x8c,
	0xce, 0x1f, 0x85, 0xd1, 0xfe, 0xbb, 0x2e, 0x7c, 0xff, 0xea, 0xd9, 0x35, 0x24, 0xfd, 0xec, 0xe9,
	0x09, 0x1c, 0xaf, 0x16, 0xef, 0xae, 0x16, 0x1f, 0xae, 0x16, 0xe4, 0x0e, 0x1d, 0xc1, 0xd1, 0x25,
	0x5b, 0xcc, 0xe6, 0x8b, 0xb7, 0x24, 0x72, 0x12, 0x67, 0x39, 0x9b, 0x7f, 0x64, 0x33, 0x72, 0xe0,
	0xa4, 0x65, 0x31, 0xe5, 0x05, 0x9b, 0x91, 0x98, 0x26, 0x30, 0xe4, 0xac, 0xe0, 0x9f, 0xc8, 0xc0,
	0xf3, 0xab, 0x3c, 0x67, 0xcb, 0x25, 0x19, 0x3a, 0x70, 0x31, 0x9d, 0xbf, 0x5f, 0x71, 0x46, 0x0e,
	0xbf, 0x1e, 0xfa, 0xcf, 0xf0, 0xea, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x7a, 0xbc, 0xe7,
	0x23, 0x03, 0x00, 0x00,
}
